(() => {
  "use strict";
  const courses = [
    {title:"Santander Open Academy",platform:"Santander",category:"Tecnologia, idiomas e negócios",description:"Cursos, conteúdos e bolsas para desenvolver competências profissionais no seu ritmo.",url:"https://www.santanderopenacademy.com/pt_br/index.html",cert:"check",certLabel:"Certificado conforme a oferta",icon:"SO",tone:"green"},
    {title:"FGV Cursos Gratuitos",platform:"Fundação Getulio Vargas",category:"Formação geral",description:"Conteúdos de formação em diferentes áreas com a credibilidade da FGV.",url:"https://cursosgratuitos.fgv.br/",cert:"check",certLabel:"Confira o certificado",icon:"FGV",tone:"blue"},
    {title:"Nação Fluente",platform:"Nação Fluente",category:"Idiomas",description:"Material com organização de vídeos para estudar inglês no YouTube.",url:"https://www.nacaofluente.com/blog/como-aprender-ingles-no-youtube/",cert:"material",certLabel:"Material gratuito",icon:"NF",tone:"violet"},
    {title:"Senar EAD",platform:"Senar",category:"Qualificação profissional",description:"Capacitações a distância para formação, gestão, produção e desenvolvimento profissional.",url:"https://ead.senar.org.br/cursos",cert:"check",certLabel:"Certificado conforme o curso",icon:"SN",tone:"gold"},
    {title:"Sebrae Paraíba",platform:"Sebrae",category:"Empreendedorismo",description:"Cursos online para empreendedorismo, gestão, negócios e desenvolvimento de ideias.",url:"https://pb.loja.sebrae.com.br/cursos/cursos-online",cert:"check",certLabel:"Confira as condições",icon:"SE",tone:"orange"},
    {title:"Escola Virtual Fundação Bradesco",platform:"Fundação Bradesco",category:"Tecnologia e produtividade",description:"Formação gratuita em tecnologia, produtividade, negócios e desenvolvimento pessoal.",url:"https://www.ev.org.br/cursos",cert:"free",certLabel:"Certificado de conclusão",icon:"EV",tone:"red"},
    {title:"UEMP",platform:"UEMP",category:"Cursos livres",description:"Cursos online gratuitos em diversas áreas, com regras próprias para certificação.",url:"https://cursosgratis.uemp.com.br/",cert:"check",certLabel:"Certificado conforme regras",icon:"UE",tone:"teal"},
    {title:"MEC Idiomas",platform:"Ministério da Educação",category:"Idiomas",description:"Plataforma de idiomas do MEC para apoiar o aprendizado e a prática de línguas.",url:"https://mecidiomas.mec.gov.br/login",cert:"check",certLabel:"Acesse e confira",icon:"MEC",tone:"blue"},
    {title:"Aprenda Mais MEC",platform:"Ministério da Educação",category:"Formação e educação",description:"Cursos abertos e gratuitos para ampliar conhecimentos e apoiar a formação.",url:"https://aprendamais.mec.gov.br/",cert:"check",certLabel:"Certificado conforme a oferta",icon:"AM",tone:"green"},
    {title:"HCX FMUSP",platform:"Hospital das Clínicas FMUSP",category:"Saúde e educação",description:"Cursos EAD gratuitos ligados à saúde, à educação e à atualização profissional.",url:"https://ensino.hcxfmusp.org.br/online/cursos/ead/gratuitos",cert:"check",certLabel:"Certificado conforme o curso",icon:"HCX",tone:"red"},
    {title:"Cruzeiro do Sul Virtual",platform:"Cruzeiro do Sul",category:"Cursos livres",description:"Cursos livres para complementar a formação e atualizar conhecimentos.",url:"https://cursos.cruzeirodosulvirtual.com.br/cursos-livres",cert:"check",certLabel:"Confira a oferta",icon:"CS",tone:"violet"},
    {title:"Prime Cursos",platform:"Prime Cursos",category:"Cursos livres",description:"Cursos online em várias áreas, com regras próprias para acesso e certificado.",url:"https://www.primecursos.com.br/",cert:"check",certLabel:"Confira as regras",icon:"PC",tone:"gold"},
    {title:"Senac — Programa de Gratuidade",platform:"Senac",category:"Qualificação profissional",description:"Oportunidades de qualificação profissional gratuita oferecidas pelo Senac EAD.",url:"https://www.ead.senac.br/gratuito/",cert:"check",certLabel:"Certificado conforme o programa",icon:"SC",tone:"orange"},
    {title:"Coursera — cursos gratuitos",platform:"Coursera",category:"Cursos internacionais",description:"Busca por cursos de universidades e empresas. Leia as condições de cada oferta.",url:"https://www.coursera.org/courses?query=free",cert:"maybe",certLabel:"Certificado pode ser pago",icon:"CO",tone:"blue"},
    {title:"Udemy — cursos gratuitos",platform:"Udemy",category:"Tecnologia e negócios",description:"Catálogo de cursos gratuitos em vários temas para aprender no seu ritmo.",url:"https://www.udemy.com/courses/free/",cert:"maybe",certLabel:"Certificado pode não estar incluído",icon:"UD",tone:"teal"}
  ];
  const $=id=>document.getElementById(id);
  const grid=$("courseGrid"), search=$("courseSearch"), category=$("categoryFilter"), cert=$("certificateFilter"), sort=$("sortCourses"), count=$("visibleCount"), summary=$("resultsSummary"), filterCount=$("filterCount"), empty=$("emptyState");
  [...new Set(courses.map(c=>c.category))].sort((a,b)=>a.localeCompare(b,"pt-BR")).forEach(value=>{const o=document.createElement("option");o.value=value;o.textContent=value;category.append(o)});
  function card(c){const el=document.createElement("article");el.className="course-card";el.innerHTML='<div class="card-topline"><span class="course-icon tone-'+c.tone+'" aria-hidden="true">'+c.icon+'</span><span class="course-category">'+c.category+'</span></div><h3>'+c.title+'</h3><p>'+c.description+'</p><div class="course-tags"><span class="course-tag course-tag-positive">Acesso gratuito</span><span class="course-tag">'+c.certLabel+'</span></div><a class="course-link" href="'+c.url+'" target="_blank" rel="noopener noreferrer">Acessar página do curso <span aria-hidden="true">↗</span></a>';return el}
  function render(){const term=search.value.trim().toLocaleLowerCase("pt-BR"), selectedCat=category.value, selectedCert=cert.value;let list=courses.filter(c=>(!term||[c.title,c.platform,c.category,c.description].join(" ").toLocaleLowerCase("pt-BR").includes(term))&&(!selectedCat||c.category===selectedCat)&&(!selectedCert||c.cert===selectedCert));if(sort.value==="az")list.sort((a,b)=>a.title.localeCompare(b.title,"pt-BR"));if(sort.value==="category")list.sort((a,b)=>a.category.localeCompare(b.category,"pt-BR")||a.title.localeCompare(b.title,"pt-BR"));grid.replaceChildren(...list.map(card));empty.hidden=list.length!==0;count.textContent=list.length;summary.textContent=list.length+" "+(list.length===1?"opção encontrada":"opções encontradas");filterCount.textContent=[term,selectedCat,selectedCert].filter(Boolean).length}
  function clear(){search.value="";category.value="";cert.value="";sort.value="featured";render();search.focus()}
  search.addEventListener("input",render);category.addEventListener("change",render);cert.addEventListener("change",render);sort.addEventListener("change",render);$("clearFilters").addEventListener("click",clear);document.querySelector("[data-clear]").addEventListener("click",clear);render();
})();